### ISSUE TITLE
issue in deploy

### ISSUE THREAD

**Issue by vid** [freeslugs/example_truffle_drizzle#1]
```
truffle(develop)> deploy

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

TypeError: this.determineDryRunSettings is not a function
    at Contracts.compile.then (/home/vid/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:184:10)                                       
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by freeslugs** [comment]
no idea where this is coming from.  likely a problem with truffle. try to remove node_modules and reinstall? maybe use yarn? 

```
example_truffle_drizzle % truffle  develop
compile Truffle Develop started at http://127.0.0.1:9545/
...

truffle(develop)> compile 
truffle(develop)> test
Using network 'develop'.



  Contract: MyStringStore
    ✓ should store the string 'Hey there!' (95ms)


  1 passing (123ms)

truffle(develop)> deploy
⚠️  Important ⚠️
If you're using an HDWalletProvider, it must be Web3 1.0 enabled or your migration will hang.


Starting migrations...
======================
> Network name:    'develop'
> Network id:      4447
> Block gas limit: 6721975
```
